### ISSUE TITLE
Documentation page is not mobile-friendly

### ISSUE THREAD

**Issue by cmmartti** [PokeAPI/pokeapi.co#9]
It's fine for now because not many people will be looking up documentation on their `phones, but on smaller viewports I'd like to swap out the table of contents on the left for a stickied breadcrumbs menu bar. The breadcrumbs would show the current page section (such as "Items > Item Categories"), and clicking on each crumb would open a list of links to the crumb's sibling sections.

Working on this now.

**Comment by Naramsim** [comment]
We can drop the description of the tables
```css
thead>tr>th:nth-child(2) {
    display: none;
}

tbody>tr>td:nth-child(2) {
    display: none;
}
```

Get rid of the `display: grid` and leave the TOC on top, or replace it with a search bar.

![pokeapi co_about html iphone 6_7_8](https://user-images.githubusercontent.com/8996268/46137847-bd0e4e80-c24a-11e8-9e41-b00917a97250.png)
